# TODO: which 3.x versions are supported
# TODO: add in coverage (via codecov)
# TODO: pytest fixes (test file uses interactive stdins during test run)
# TODO: pypi deployment with successful tests on tag pushes

name: gpCAM CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '2.x', '3.7', '3.8' ]
        
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      
      - name: Set up Python 2 and 3
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install dependencies
        run: pip install -r requirements.txt
      
#       - name: Run tests
#         run: pytest
      
